[2024-11-23T22:18:03.833+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-23T22:18:03.852+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: create_bucket.save_date scheduled__2024-11-22T00:00:00+00:00 [queued]>
[2024-11-23T22:18:03.860+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: create_bucket.save_date scheduled__2024-11-22T00:00:00+00:00 [queued]>
[2024-11-23T22:18:03.861+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-11-23T22:18:03.872+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): save_date> on 2024-11-22 00:00:00+00:00
[2024-11-23T22:18:03.880+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=77) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-23T22:18:03.881+0000] {standard_task_runner.py:72} INFO - Started process 79 to run task
[2024-11-23T22:18:03.882+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'create_bucket', 'save_date', 'scheduled__2024-11-22T00:00:00+00:00', '--job-id', '47', '--raw', '--subdir', 'DAGS_FOLDER/obs.py', '--cfg-path', '/tmp/tmpr18q6a8f']
[2024-11-23T22:18:03.883+0000] {standard_task_runner.py:105} INFO - Job 47: Subtask save_date
[2024-11-23T22:18:03.931+0000] {task_command.py:467} INFO - Running <TaskInstance: create_bucket.save_date scheduled__2024-11-22T00:00:00+00:00 [running]> on host 256f0a297285
[2024-11-23T22:18:04.017+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='create_bucket' AIRFLOW_CTX_TASK_ID='save_date' AIRFLOW_CTX_EXECUTION_DATE='2024-11-22T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-22T00:00:00+00:00'
[2024-11-23T22:18:04.017+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-23T22:18:49.503+0000] {logging_mixin.py:190} INFO - Create Bucket Failed
[2024-11-23T22:18:49.503+0000] {logging_mixin.py:190} INFO - requestId: 000001935B1B31BB44D4B0B3B6C9E470
[2024-11-23T22:18:49.503+0000] {logging_mixin.py:190} INFO - errorCode: UserRestricted
[2024-11-23T22:18:49.503+0000] {logging_mixin.py:190} INFO - errorMessage: This operation is forbidden for restricted users
[2024-11-23T22:18:49.503+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-11-23T22:18:49.515+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-23T22:18:49.515+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=create_bucket, task_id=save_date, run_id=scheduled__2024-11-22T00:00:00+00:00, execution_date=20241122T000000, start_date=20241123T221803, end_date=20241123T221849
[2024-11-23T22:18:49.561+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-23T22:18:49.576+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-23T22:18:49.577+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
