[2024-11-22T17:02:30.690+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-22T17:02:30.711+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_dag.hello_world_task scheduled__2024-11-21T00:00:00+00:00 [queued]>
[2024-11-22T17:02:30.721+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_dag.hello_world_task scheduled__2024-11-21T00:00:00+00:00 [queued]>
[2024-11-22T17:02:30.722+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-11-22T17:02:30.735+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): hello_world_task> on 2024-11-21 00:00:00+00:00
[2024-11-22T17:02:30.745+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=365) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-22T17:02:30.746+0000] {standard_task_runner.py:72} INFO - Started process 366 to run task
[2024-11-22T17:02:30.748+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'hello_world_task', 'scheduled__2024-11-21T00:00:00+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpc_yza3c6']
[2024-11-22T17:02:30.749+0000] {standard_task_runner.py:105} INFO - Job 29: Subtask hello_world_task
[2024-11-22T17:02:30.804+0000] {task_command.py:467} INFO - Running <TaskInstance: my_dag.hello_world_task scheduled__2024-11-21T00:00:00+00:00 [running]> on host 0276b599ff7e
[2024-11-22T17:02:30.899+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_dag' AIRFLOW_CTX_TASK_ID='hello_world_task' AIRFLOW_CTX_EXECUTION_DATE='2024-11-21T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-21T00:00:00+00:00'
[2024-11-22T17:02:30.900+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-22T17:02:30.914+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2024-11-22T17:02:30.915+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'python -c "print(\'Hello, world!\')"']
[2024-11-22T17:02:30.934+0000] {subprocess.py:99} INFO - Output:
[2024-11-22T17:02:30.963+0000] {subprocess.py:106} INFO - Hello, world!
[2024-11-22T17:02:30.966+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2024-11-22T17:02:30.999+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-22T17:02:30.999+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=hello_world_task, run_id=scheduled__2024-11-21T00:00:00+00:00, execution_date=20241121T000000, start_date=20241122T170230, end_date=20241122T170230
[2024-11-22T17:02:31.042+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-22T17:02:31.063+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-22T17:02:31.064+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
