[2024-11-22T17:02:26.220+0000] {processor.py:186} INFO - Started process (PID=420) to work on /opt/airflow/dags/obs.py
[2024-11-22T17:02:26.222+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-22T17:02:26.227+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:02:26.226+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-22T17:02:26.282+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:02:26.278+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-22T17:02:26.284+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-22T17:02:26.326+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.120 seconds
[2024-11-22T17:02:56.586+0000] {processor.py:186} INFO - Started process (PID=428) to work on /opt/airflow/dags/obs.py
[2024-11-22T17:02:56.587+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-22T17:02:56.590+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:02:56.590+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-22T17:02:56.616+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:02:56.615+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-22T17:02:56.617+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-22T17:02:56.640+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.060 seconds
[2024-11-22T17:03:26.891+0000] {processor.py:186} INFO - Started process (PID=436) to work on /opt/airflow/dags/obs.py
[2024-11-22T17:03:26.938+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-22T17:03:26.941+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:03:26.941+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-22T17:03:26.962+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:03:26.961+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-22T17:03:26.963+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-22T17:03:26.980+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.094 seconds
[2024-11-22T17:03:57.206+0000] {processor.py:186} INFO - Started process (PID=444) to work on /opt/airflow/dags/obs.py
[2024-11-22T17:03:57.207+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-22T17:03:57.210+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:03:57.210+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-22T17:03:57.232+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:03:57.231+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-22T17:03:57.232+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-22T17:03:57.250+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.050 seconds
[2024-11-22T17:04:27.518+0000] {processor.py:186} INFO - Started process (PID=452) to work on /opt/airflow/dags/obs.py
[2024-11-22T17:04:27.527+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-22T17:04:27.531+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:04:27.530+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-22T17:04:27.561+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:04:27.560+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-22T17:04:27.561+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-22T17:04:27.587+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.077 seconds
[2024-11-22T17:04:57.853+0000] {processor.py:186} INFO - Started process (PID=460) to work on /opt/airflow/dags/obs.py
[2024-11-22T17:04:57.854+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-22T17:04:57.859+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:04:57.859+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-22T17:04:57.885+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:04:57.884+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-22T17:04:57.885+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-22T17:04:57.907+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.060 seconds
[2024-11-22T17:05:28.173+0000] {processor.py:186} INFO - Started process (PID=468) to work on /opt/airflow/dags/obs.py
[2024-11-22T17:05:28.221+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-22T17:05:28.225+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:05:28.225+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-22T17:05:28.250+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:05:28.249+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-22T17:05:28.251+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-22T17:05:28.274+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.108 seconds
[2024-11-22T17:05:58.530+0000] {processor.py:186} INFO - Started process (PID=476) to work on /opt/airflow/dags/obs.py
[2024-11-22T17:05:58.530+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-22T17:05:58.533+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:05:58.532+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-22T17:05:58.558+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:05:58.557+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-22T17:05:58.559+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-22T17:05:58.580+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.056 seconds
[2024-11-22T17:06:28.833+0000] {processor.py:186} INFO - Started process (PID=484) to work on /opt/airflow/dags/obs.py
[2024-11-22T17:06:28.892+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-22T17:06:28.895+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:06:28.895+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-22T17:06:28.916+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:06:28.915+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-22T17:06:28.916+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-22T17:06:28.934+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.106 seconds
[2024-11-22T17:06:59.185+0000] {processor.py:186} INFO - Started process (PID=492) to work on /opt/airflow/dags/obs.py
[2024-11-22T17:06:59.186+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-22T17:06:59.189+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:06:59.189+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-22T17:06:59.211+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:06:59.211+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-22T17:06:59.212+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-22T17:06:59.229+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.049 seconds
[2024-11-22T17:07:29.478+0000] {processor.py:186} INFO - Started process (PID=500) to work on /opt/airflow/dags/obs.py
[2024-11-22T17:07:29.525+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-22T17:07:29.528+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:07:29.528+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-22T17:07:29.553+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:07:29.552+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-22T17:07:29.555+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-22T17:07:29.579+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.107 seconds
[2024-11-22T17:07:59.844+0000] {processor.py:186} INFO - Started process (PID=508) to work on /opt/airflow/dags/obs.py
[2024-11-22T17:07:59.845+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-22T17:07:59.849+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:07:59.848+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-22T17:07:59.874+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:07:59.873+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-22T17:07:59.875+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-22T17:07:59.895+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.059 seconds
[2024-11-22T17:08:30.152+0000] {processor.py:186} INFO - Started process (PID=517) to work on /opt/airflow/dags/obs.py
[2024-11-22T17:08:30.163+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-22T17:08:30.167+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:08:30.167+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-22T17:08:30.193+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:08:30.192+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-22T17:08:30.193+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-22T17:08:30.218+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.072 seconds
[2024-11-22T17:09:00.490+0000] {processor.py:186} INFO - Started process (PID=525) to work on /opt/airflow/dags/obs.py
[2024-11-22T17:09:00.491+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-22T17:09:00.494+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:09:00.493+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-22T17:09:00.522+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:09:00.521+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-22T17:09:00.522+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-22T17:09:00.545+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.062 seconds
[2024-11-22T17:09:30.811+0000] {processor.py:186} INFO - Started process (PID=533) to work on /opt/airflow/dags/obs.py
[2024-11-22T17:09:30.858+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-22T17:09:30.862+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:09:30.862+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-22T17:09:30.887+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:09:30.886+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-22T17:09:30.888+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-22T17:09:30.910+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.106 seconds
[2024-11-22T17:10:01.174+0000] {processor.py:186} INFO - Started process (PID=541) to work on /opt/airflow/dags/obs.py
[2024-11-22T17:10:01.175+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-22T17:10:01.178+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:10:01.178+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-22T17:10:01.203+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:10:01.202+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-22T17:10:01.204+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-22T17:10:01.226+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.059 seconds
[2024-11-22T17:10:31.489+0000] {processor.py:186} INFO - Started process (PID=549) to work on /opt/airflow/dags/obs.py
[2024-11-22T17:10:31.536+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-22T17:10:31.541+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:10:31.540+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-22T17:10:31.562+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:10:31.561+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-22T17:10:31.562+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-22T17:10:31.579+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.095 seconds
[2024-11-22T17:11:01.862+0000] {processor.py:186} INFO - Started process (PID=557) to work on /opt/airflow/dags/obs.py
[2024-11-22T17:11:01.863+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-22T17:11:01.867+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:11:01.867+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-22T17:11:01.896+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:11:01.895+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-22T17:11:01.897+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-22T17:11:01.921+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.067 seconds
[2024-11-22T17:11:32.191+0000] {processor.py:186} INFO - Started process (PID=565) to work on /opt/airflow/dags/obs.py
[2024-11-22T17:11:32.239+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-22T17:11:32.244+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:11:32.244+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-22T17:11:32.270+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:11:32.269+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-22T17:11:32.271+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-22T17:11:32.293+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.109 seconds
[2024-11-22T17:12:02.551+0000] {processor.py:186} INFO - Started process (PID=573) to work on /opt/airflow/dags/obs.py
[2024-11-22T17:12:02.552+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-22T17:12:02.555+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:12:02.554+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-22T17:12:02.583+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:12:02.582+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-22T17:12:02.584+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-22T17:12:02.606+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.062 seconds
[2024-11-22T17:12:32.871+0000] {processor.py:186} INFO - Started process (PID=581) to work on /opt/airflow/dags/obs.py
[2024-11-22T17:12:32.919+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-22T17:12:32.923+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:12:32.923+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-22T17:12:32.949+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:12:32.948+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-22T17:12:32.949+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-22T17:12:32.972+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.106 seconds
[2024-11-22T17:13:03.242+0000] {processor.py:186} INFO - Started process (PID=589) to work on /opt/airflow/dags/obs.py
[2024-11-22T17:13:03.244+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-22T17:13:03.249+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:13:03.248+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-22T17:13:03.276+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:13:03.274+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-22T17:13:03.277+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-22T17:13:03.301+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.066 seconds
[2024-11-22T17:13:33.556+0000] {processor.py:186} INFO - Started process (PID=597) to work on /opt/airflow/dags/obs.py
[2024-11-22T17:13:33.557+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-22T17:13:33.559+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:13:33.559+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-22T17:13:33.583+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:13:33.582+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-22T17:13:33.583+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-22T17:13:33.599+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.048 seconds
[2024-11-22T17:14:03.859+0000] {processor.py:186} INFO - Started process (PID=605) to work on /opt/airflow/dags/obs.py
[2024-11-22T17:14:03.861+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-22T17:14:03.865+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:14:03.864+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-22T17:14:03.890+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:14:03.888+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-22T17:14:03.890+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-22T17:14:03.913+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.061 seconds
[2024-11-22T17:14:34.180+0000] {processor.py:186} INFO - Started process (PID=613) to work on /opt/airflow/dags/obs.py
[2024-11-22T17:14:34.227+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-22T17:14:34.231+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:14:34.230+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-22T17:14:34.257+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:14:34.255+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-22T17:14:34.258+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-22T17:14:34.281+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.108 seconds
[2024-11-22T17:15:04.533+0000] {processor.py:186} INFO - Started process (PID=621) to work on /opt/airflow/dags/obs.py
[2024-11-22T17:15:04.534+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-22T17:15:04.537+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:15:04.537+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-22T17:15:04.565+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:15:04.564+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-22T17:15:04.565+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-22T17:15:04.587+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.062 seconds
[2024-11-22T17:15:34.858+0000] {processor.py:186} INFO - Started process (PID=629) to work on /opt/airflow/dags/obs.py
[2024-11-22T17:15:34.905+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-22T17:15:34.911+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:15:34.910+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-22T17:15:34.935+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:15:34.934+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-22T17:15:34.935+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-22T17:15:34.959+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.108 seconds
[2024-11-22T17:16:05.222+0000] {processor.py:186} INFO - Started process (PID=637) to work on /opt/airflow/dags/obs.py
[2024-11-22T17:16:05.223+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-22T17:16:05.228+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:16:05.227+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-22T17:16:05.254+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:16:05.253+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-22T17:16:05.254+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-22T17:16:05.278+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.062 seconds
[2024-11-22T17:16:35.541+0000] {processor.py:186} INFO - Started process (PID=645) to work on /opt/airflow/dags/obs.py
[2024-11-22T17:16:35.588+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-22T17:16:35.592+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:16:35.592+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-22T17:16:35.620+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:16:35.619+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-22T17:16:35.620+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-22T17:16:35.642+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.108 seconds
[2024-11-22T17:17:05.903+0000] {processor.py:186} INFO - Started process (PID=653) to work on /opt/airflow/dags/obs.py
[2024-11-22T17:17:05.904+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-22T17:17:05.907+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:17:05.907+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-22T17:17:05.946+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:17:05.938+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-22T17:17:05.948+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-22T17:17:05.970+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.074 seconds
[2024-11-22T17:17:36.240+0000] {processor.py:186} INFO - Started process (PID=661) to work on /opt/airflow/dags/obs.py
[2024-11-22T17:17:36.288+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-22T17:17:36.293+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:17:36.292+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-22T17:17:36.322+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:17:36.321+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-22T17:17:36.323+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-22T17:17:36.348+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.115 seconds
[2024-11-22T17:18:06.617+0000] {processor.py:186} INFO - Started process (PID=670) to work on /opt/airflow/dags/obs.py
[2024-11-22T17:18:06.618+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-22T17:18:06.621+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:18:06.621+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-22T17:18:06.651+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:18:06.649+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-22T17:18:06.651+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-22T17:18:06.675+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.066 seconds
[2024-11-22T17:18:36.946+0000] {processor.py:186} INFO - Started process (PID=678) to work on /opt/airflow/dags/obs.py
[2024-11-22T17:18:36.993+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-22T17:18:36.998+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:18:36.998+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-22T17:18:37.039+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:18:37.037+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-22T17:18:37.040+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-22T17:18:37.072+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.134 seconds
[2024-11-22T17:19:07.336+0000] {processor.py:186} INFO - Started process (PID=686) to work on /opt/airflow/dags/obs.py
[2024-11-22T17:19:07.337+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-22T17:19:07.340+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:19:07.340+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-22T17:19:07.367+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:19:07.366+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-22T17:19:07.368+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-22T17:19:07.390+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.061 seconds
[2024-11-22T17:19:37.642+0000] {processor.py:186} INFO - Started process (PID=694) to work on /opt/airflow/dags/obs.py
[2024-11-22T17:19:37.655+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-22T17:19:37.660+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:19:37.659+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-22T17:19:37.687+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:19:37.686+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-22T17:19:37.687+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-22T17:19:37.711+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.076 seconds
[2024-11-22T17:20:07.963+0000] {processor.py:186} INFO - Started process (PID=702) to work on /opt/airflow/dags/obs.py
[2024-11-22T17:20:07.964+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-22T17:20:07.967+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:20:07.966+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-22T17:20:08.017+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:20:08.016+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-22T17:20:08.018+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-22T17:20:08.036+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.079 seconds
[2024-11-22T17:20:38.303+0000] {processor.py:186} INFO - Started process (PID=716) to work on /opt/airflow/dags/obs.py
[2024-11-22T17:20:38.350+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-22T17:20:38.354+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:20:38.354+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-22T17:20:38.381+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:20:38.380+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-22T17:20:38.381+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-22T17:20:38.403+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.107 seconds
[2024-11-22T17:21:08.661+0000] {processor.py:186} INFO - Started process (PID=724) to work on /opt/airflow/dags/obs.py
[2024-11-22T17:21:08.663+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-22T17:21:08.666+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:21:08.666+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-22T17:21:08.694+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:21:08.692+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-22T17:21:08.694+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-22T17:21:08.716+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.062 seconds
[2024-11-22T17:21:38.986+0000] {processor.py:186} INFO - Started process (PID=732) to work on /opt/airflow/dags/obs.py
[2024-11-22T17:21:39.033+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-22T17:21:39.037+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:21:39.036+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-22T17:21:39.063+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:21:39.062+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-22T17:21:39.064+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-22T17:21:39.088+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.108 seconds
[2024-11-22T17:22:09.368+0000] {processor.py:186} INFO - Started process (PID=740) to work on /opt/airflow/dags/obs.py
[2024-11-22T17:22:09.368+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-22T17:22:09.372+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:22:09.372+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-22T17:22:09.397+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:22:09.395+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-22T17:22:09.397+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-22T17:22:09.420+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.060 seconds
[2024-11-22T17:22:39.680+0000] {processor.py:186} INFO - Started process (PID=748) to work on /opt/airflow/dags/obs.py
[2024-11-22T17:22:39.728+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-22T17:22:39.732+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:22:39.732+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-22T17:22:39.757+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:22:39.756+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-22T17:22:39.758+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-22T17:22:39.779+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.106 seconds
[2024-11-22T17:23:10.045+0000] {processor.py:186} INFO - Started process (PID=756) to work on /opt/airflow/dags/obs.py
[2024-11-22T17:23:10.047+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-22T17:23:10.051+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:23:10.050+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-22T17:23:10.075+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:23:10.074+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-22T17:23:10.075+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-22T17:23:10.097+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.058 seconds
[2024-11-22T17:23:40.345+0000] {processor.py:186} INFO - Started process (PID=764) to work on /opt/airflow/dags/obs.py
[2024-11-22T17:23:40.391+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-22T17:23:40.393+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:23:40.393+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-22T17:23:40.415+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:23:40.414+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-22T17:23:40.415+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-22T17:23:40.433+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.093 seconds
[2024-11-22T17:24:10.707+0000] {processor.py:186} INFO - Started process (PID=772) to work on /opt/airflow/dags/obs.py
[2024-11-22T17:24:10.708+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-22T17:24:10.711+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:24:10.710+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-22T17:24:10.743+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:24:10.742+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-22T17:24:10.743+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-22T17:24:10.771+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.072 seconds
[2024-11-22T17:24:41.042+0000] {processor.py:186} INFO - Started process (PID=780) to work on /opt/airflow/dags/obs.py
[2024-11-22T17:24:41.089+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-22T17:24:41.093+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:24:41.093+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-22T17:24:41.120+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:24:41.119+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-22T17:24:41.121+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-22T17:24:41.143+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.108 seconds
[2024-11-22T17:25:11.407+0000] {processor.py:186} INFO - Started process (PID=788) to work on /opt/airflow/dags/obs.py
[2024-11-22T17:25:11.408+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-22T17:25:11.411+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:25:11.411+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-22T17:25:11.437+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:25:11.436+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-22T17:25:11.437+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-22T17:25:11.459+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.060 seconds
[2024-11-22T17:25:41.719+0000] {processor.py:186} INFO - Started process (PID=796) to work on /opt/airflow/dags/obs.py
[2024-11-22T17:25:41.766+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-22T17:25:41.769+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:25:41.769+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-22T17:25:41.793+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:25:41.792+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-22T17:25:41.794+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-22T17:25:41.816+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.105 seconds
[2024-11-22T17:26:12.083+0000] {processor.py:186} INFO - Started process (PID=804) to work on /opt/airflow/dags/obs.py
[2024-11-22T17:26:12.084+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-22T17:26:12.088+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:26:12.087+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-22T17:26:12.113+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:26:12.111+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-22T17:26:12.113+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-22T17:26:12.135+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.060 seconds
[2024-11-22T17:26:42.399+0000] {processor.py:186} INFO - Started process (PID=812) to work on /opt/airflow/dags/obs.py
[2024-11-22T17:26:42.447+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-22T17:26:42.451+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:26:42.451+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-22T17:26:42.475+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:26:42.474+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-22T17:26:42.476+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-22T17:26:42.498+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.106 seconds
[2024-11-22T17:27:12.750+0000] {processor.py:186} INFO - Started process (PID=820) to work on /opt/airflow/dags/obs.py
[2024-11-22T17:27:12.750+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-22T17:27:12.753+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:27:12.752+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-22T17:27:12.776+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:27:12.775+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-22T17:27:12.776+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-22T17:27:12.795+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.051 seconds
[2024-11-22T17:27:43.070+0000] {processor.py:186} INFO - Started process (PID=828) to work on /opt/airflow/dags/obs.py
[2024-11-22T17:27:43.088+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-22T17:27:43.092+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:27:43.092+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-22T17:27:43.118+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:27:43.117+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-22T17:27:43.119+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-22T17:27:43.139+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.077 seconds
[2024-11-22T17:28:13.409+0000] {processor.py:186} INFO - Started process (PID=836) to work on /opt/airflow/dags/obs.py
[2024-11-22T17:28:13.410+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-22T17:28:13.414+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:28:13.414+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-22T17:28:13.439+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:28:13.438+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-22T17:28:13.439+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-22T17:28:13.462+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.059 seconds
[2024-11-22T17:28:43.734+0000] {processor.py:186} INFO - Started process (PID=844) to work on /opt/airflow/dags/obs.py
[2024-11-22T17:28:43.781+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-22T17:28:43.785+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:28:43.785+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-22T17:28:43.811+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:28:43.810+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-22T17:28:43.811+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-22T17:28:43.834+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.107 seconds
[2024-11-22T17:29:14.096+0000] {processor.py:186} INFO - Started process (PID=852) to work on /opt/airflow/dags/obs.py
[2024-11-22T17:29:14.097+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-22T17:29:14.102+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:29:14.101+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-22T17:29:14.128+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:29:14.127+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-22T17:29:14.128+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-22T17:29:14.151+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.061 seconds
[2024-11-22T17:29:44.415+0000] {processor.py:186} INFO - Started process (PID=860) to work on /opt/airflow/dags/obs.py
[2024-11-22T17:29:44.463+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-22T17:29:44.467+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:29:44.467+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-22T17:29:44.495+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:29:44.493+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-22T17:29:44.495+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-22T17:29:44.518+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.109 seconds
[2024-11-22T17:30:14.782+0000] {processor.py:186} INFO - Started process (PID=868) to work on /opt/airflow/dags/obs.py
[2024-11-22T17:30:14.783+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-22T17:30:14.786+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:30:14.785+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-22T17:30:14.835+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:30:14.834+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-22T17:30:14.836+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-22T17:30:14.873+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.096 seconds
[2024-11-22T17:30:45.141+0000] {processor.py:186} INFO - Started process (PID=876) to work on /opt/airflow/dags/obs.py
[2024-11-22T17:30:45.189+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-22T17:30:45.193+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:30:45.193+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-22T17:30:45.222+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:30:45.221+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-22T17:30:45.223+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-22T17:30:45.247+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.115 seconds
[2024-11-22T17:31:15.512+0000] {processor.py:186} INFO - Started process (PID=884) to work on /opt/airflow/dags/obs.py
[2024-11-22T17:31:15.513+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-22T17:31:15.518+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:31:15.517+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-22T17:31:15.543+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:31:15.542+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-22T17:31:15.544+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-22T17:31:15.567+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.060 seconds
[2024-11-22T17:31:45.835+0000] {processor.py:186} INFO - Started process (PID=892) to work on /opt/airflow/dags/obs.py
[2024-11-22T17:31:45.883+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-22T17:31:45.886+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:31:45.886+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-22T17:31:45.910+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:31:45.909+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-22T17:31:45.911+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-22T17:31:45.931+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.102 seconds
[2024-11-22T17:32:16.187+0000] {processor.py:186} INFO - Started process (PID=900) to work on /opt/airflow/dags/obs.py
[2024-11-22T17:32:16.188+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-22T17:32:16.191+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:32:16.191+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-22T17:32:16.214+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:32:16.213+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-22T17:32:16.214+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-22T17:32:16.233+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.053 seconds
[2024-11-22T17:32:46.498+0000] {processor.py:186} INFO - Started process (PID=908) to work on /opt/airflow/dags/obs.py
[2024-11-22T17:32:46.545+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-22T17:32:46.550+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:32:46.549+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-22T17:32:46.574+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:32:46.573+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-22T17:32:46.575+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-22T17:32:46.595+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.104 seconds
[2024-11-22T17:33:16.862+0000] {processor.py:186} INFO - Started process (PID=916) to work on /opt/airflow/dags/obs.py
[2024-11-22T17:33:16.863+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-22T17:33:16.867+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:33:16.866+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-22T17:33:16.906+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:33:16.904+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-22T17:33:16.907+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-22T17:33:16.935+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.080 seconds
[2024-11-22T17:33:47.180+0000] {processor.py:186} INFO - Started process (PID=923) to work on /opt/airflow/dags/obs.py
[2024-11-22T17:33:47.181+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-22T17:33:47.184+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:33:47.184+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-22T17:33:47.208+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:33:47.207+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-22T17:33:47.208+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-22T17:33:47.229+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.055 seconds
[2024-11-22T17:34:17.493+0000] {processor.py:186} INFO - Started process (PID=931) to work on /opt/airflow/dags/obs.py
[2024-11-22T17:34:17.494+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-22T17:34:17.499+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:34:17.498+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-22T17:34:17.529+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:34:17.528+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-22T17:34:17.530+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-22T17:34:17.556+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.071 seconds
[2024-11-22T17:34:47.843+0000] {processor.py:186} INFO - Started process (PID=939) to work on /opt/airflow/dags/obs.py
[2024-11-22T17:34:47.890+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-22T17:34:47.894+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:34:47.893+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-22T17:34:47.917+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:34:47.916+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-22T17:34:47.918+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-22T17:34:47.939+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.103 seconds
[2024-11-22T17:35:18.233+0000] {processor.py:186} INFO - Started process (PID=947) to work on /opt/airflow/dags/obs.py
[2024-11-22T17:35:18.234+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-22T17:35:18.238+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:35:18.237+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-22T17:35:18.262+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:35:18.261+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-22T17:35:18.263+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-22T17:35:18.282+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.055 seconds
[2024-11-22T17:35:48.534+0000] {processor.py:186} INFO - Started process (PID=955) to work on /opt/airflow/dags/obs.py
[2024-11-22T17:35:48.586+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-22T17:35:48.590+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:35:48.590+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-22T17:35:48.617+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:35:48.616+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-22T17:35:48.618+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-22T17:35:48.639+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.111 seconds
[2024-11-22T17:36:18.897+0000] {processor.py:186} INFO - Started process (PID=963) to work on /opt/airflow/dags/obs.py
[2024-11-22T17:36:18.898+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-22T17:36:18.900+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:36:18.900+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-22T17:36:18.928+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:36:18.927+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-22T17:36:18.929+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-22T17:36:18.950+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.061 seconds
[2024-11-22T17:36:49.699+0000] {processor.py:186} INFO - Started process (PID=971) to work on /opt/airflow/dags/obs.py
[2024-11-22T17:36:49.747+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-22T17:36:49.751+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:36:49.751+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-22T17:36:49.775+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:36:49.774+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-22T17:36:49.776+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-22T17:36:49.798+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.104 seconds
[2024-11-22T17:37:20.105+0000] {processor.py:186} INFO - Started process (PID=979) to work on /opt/airflow/dags/obs.py
[2024-11-22T17:37:20.106+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-22T17:37:20.109+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:37:20.108+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-22T17:37:20.180+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:37:20.179+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-22T17:37:20.181+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-22T17:37:20.219+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.125 seconds
[2024-11-22T17:37:50.502+0000] {processor.py:186} INFO - Started process (PID=987) to work on /opt/airflow/dags/obs.py
[2024-11-22T17:37:50.549+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-22T17:37:50.553+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:37:50.552+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-22T17:37:50.589+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:37:50.588+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-22T17:37:50.590+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-22T17:37:50.616+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.122 seconds
[2024-11-22T17:38:20.873+0000] {processor.py:186} INFO - Started process (PID=995) to work on /opt/airflow/dags/obs.py
[2024-11-22T17:38:20.873+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-22T17:38:20.877+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:38:20.876+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-22T17:38:20.900+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:38:20.899+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-22T17:38:20.900+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-22T17:38:20.918+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.050 seconds
[2024-11-22T17:38:51.217+0000] {processor.py:186} INFO - Started process (PID=1003) to work on /opt/airflow/dags/obs.py
[2024-11-22T17:38:51.264+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-22T17:38:51.268+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:38:51.268+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-22T17:38:51.295+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:38:51.294+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-22T17:38:51.295+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-22T17:38:51.317+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.108 seconds
[2024-11-22T17:39:21.579+0000] {processor.py:186} INFO - Started process (PID=1011) to work on /opt/airflow/dags/obs.py
[2024-11-22T17:39:21.580+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-22T17:39:21.583+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:39:21.583+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-22T17:39:21.606+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:39:21.605+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-22T17:39:21.606+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-22T17:39:21.628+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.055 seconds
[2024-11-22T17:39:51.898+0000] {processor.py:186} INFO - Started process (PID=1019) to work on /opt/airflow/dags/obs.py
[2024-11-22T17:39:51.917+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-22T17:39:51.921+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:39:51.920+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-22T17:39:51.951+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:39:51.950+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-22T17:39:51.952+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-22T17:39:51.977+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.089 seconds
[2024-11-22T17:40:22.242+0000] {processor.py:186} INFO - Started process (PID=1027) to work on /opt/airflow/dags/obs.py
[2024-11-22T17:40:22.243+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-22T17:40:22.245+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:40:22.245+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-22T17:40:22.271+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:40:22.270+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-22T17:40:22.271+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-22T17:40:22.299+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.063 seconds
[2024-11-22T17:40:52.558+0000] {processor.py:186} INFO - Started process (PID=1036) to work on /opt/airflow/dags/obs.py
[2024-11-22T17:40:52.583+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-22T17:40:52.586+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:40:52.585+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-22T17:40:52.606+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:40:52.605+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-22T17:40:52.606+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-22T17:40:52.623+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.071 seconds
[2024-11-22T17:41:22.879+0000] {processor.py:186} INFO - Started process (PID=1044) to work on /opt/airflow/dags/obs.py
[2024-11-22T17:41:22.880+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-22T17:41:22.884+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:41:22.883+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-22T17:41:22.906+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:41:22.905+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-22T17:41:22.906+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-22T17:41:22.926+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.052 seconds
[2024-11-22T17:41:53.188+0000] {processor.py:186} INFO - Started process (PID=1052) to work on /opt/airflow/dags/obs.py
[2024-11-22T17:41:53.204+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-22T17:41:53.207+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:41:53.207+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-22T17:41:53.232+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:41:53.231+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-22T17:41:53.232+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-22T17:41:53.254+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.072 seconds
[2024-11-22T17:42:23.542+0000] {processor.py:186} INFO - Started process (PID=1060) to work on /opt/airflow/dags/obs.py
[2024-11-22T17:42:23.543+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-22T17:42:23.547+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:42:23.546+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-22T17:42:23.573+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:42:23.572+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-22T17:42:23.574+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-22T17:42:23.597+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.062 seconds
[2024-11-22T17:42:53.863+0000] {processor.py:186} INFO - Started process (PID=1068) to work on /opt/airflow/dags/obs.py
[2024-11-22T17:42:53.910+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-22T17:42:53.914+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:42:53.913+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-22T17:42:53.937+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:42:53.936+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-22T17:42:53.937+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-22T17:42:53.958+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.102 seconds
[2024-11-22T17:43:24.212+0000] {processor.py:186} INFO - Started process (PID=1076) to work on /opt/airflow/dags/obs.py
[2024-11-22T17:43:24.213+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-22T17:43:24.216+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:43:24.215+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-22T17:43:24.239+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:43:24.238+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-22T17:43:24.239+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-22T17:43:24.259+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.053 seconds
[2024-11-22T17:43:54.515+0000] {processor.py:186} INFO - Started process (PID=1084) to work on /opt/airflow/dags/obs.py
[2024-11-22T17:43:54.563+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-22T17:43:54.567+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:43:54.567+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-22T17:43:54.593+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:43:54.592+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-22T17:43:54.593+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-22T17:43:54.617+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.108 seconds
[2024-11-22T17:44:24.873+0000] {processor.py:186} INFO - Started process (PID=1092) to work on /opt/airflow/dags/obs.py
[2024-11-22T17:44:24.873+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-22T17:44:24.877+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:44:24.876+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-22T17:44:24.900+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:44:24.899+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-22T17:44:24.900+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-22T17:44:24.921+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.055 seconds
[2024-11-22T17:44:55.185+0000] {processor.py:186} INFO - Started process (PID=1100) to work on /opt/airflow/dags/obs.py
[2024-11-22T17:44:55.231+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-22T17:44:55.235+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:44:55.235+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-22T17:44:55.260+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:44:55.259+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-22T17:44:55.261+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-22T17:44:55.284+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.105 seconds
[2024-11-22T17:45:25.549+0000] {processor.py:186} INFO - Started process (PID=1108) to work on /opt/airflow/dags/obs.py
[2024-11-22T17:45:25.550+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-22T17:45:25.554+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:45:25.553+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-22T17:45:25.579+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:45:25.578+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-22T17:45:25.580+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-22T17:45:25.600+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.057 seconds
[2024-11-22T17:45:55.863+0000] {processor.py:186} INFO - Started process (PID=1116) to work on /opt/airflow/dags/obs.py
[2024-11-22T17:45:55.911+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-22T17:45:55.915+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:45:55.914+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-22T17:45:55.939+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:45:55.938+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-22T17:45:55.940+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-22T17:45:55.962+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.105 seconds
[2024-11-22T17:46:26.215+0000] {processor.py:186} INFO - Started process (PID=1124) to work on /opt/airflow/dags/obs.py
[2024-11-22T17:46:26.216+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-22T17:46:26.218+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:46:26.218+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-22T17:46:26.245+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:46:26.244+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-22T17:46:26.246+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-22T17:46:26.266+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.058 seconds
[2024-11-22T17:46:56.534+0000] {processor.py:186} INFO - Started process (PID=1132) to work on /opt/airflow/dags/obs.py
[2024-11-22T17:46:56.581+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-22T17:46:56.585+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:46:56.585+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-22T17:46:56.609+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:46:56.608+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-22T17:46:56.609+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-22T17:46:56.630+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.103 seconds
[2024-11-22T17:47:26.879+0000] {processor.py:186} INFO - Started process (PID=1140) to work on /opt/airflow/dags/obs.py
[2024-11-22T17:47:26.880+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-22T17:47:26.882+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:47:26.882+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-22T17:47:26.902+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:47:26.902+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-22T17:47:26.903+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-22T17:47:26.919+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.045 seconds
[2024-11-22T17:47:57.170+0000] {processor.py:186} INFO - Started process (PID=1148) to work on /opt/airflow/dags/obs.py
[2024-11-22T17:47:57.172+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-22T17:47:57.175+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:47:57.174+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-22T17:47:57.200+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:47:57.199+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-22T17:47:57.200+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-22T17:47:57.220+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.057 seconds
[2024-11-22T17:48:27.481+0000] {processor.py:186} INFO - Started process (PID=1156) to work on /opt/airflow/dags/obs.py
[2024-11-22T17:48:27.482+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-22T17:48:27.486+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:48:27.485+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-22T17:48:27.509+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:48:27.508+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-22T17:48:27.509+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-22T17:48:27.534+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.059 seconds
[2024-11-22T17:48:57.790+0000] {processor.py:186} INFO - Started process (PID=1164) to work on /opt/airflow/dags/obs.py
[2024-11-22T17:48:57.791+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-22T17:48:57.795+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:48:57.795+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-22T17:48:57.819+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:48:57.818+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-22T17:48:57.819+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-22T17:48:57.840+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.056 seconds
[2024-11-22T17:49:28.104+0000] {processor.py:186} INFO - Started process (PID=1172) to work on /opt/airflow/dags/obs.py
[2024-11-22T17:49:28.105+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-22T17:49:28.108+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:49:28.107+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-22T17:49:28.131+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:49:28.130+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-22T17:49:28.132+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-22T17:49:28.152+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.055 seconds
[2024-11-22T17:49:58.458+0000] {processor.py:186} INFO - Started process (PID=1180) to work on /opt/airflow/dags/obs.py
[2024-11-22T17:49:58.536+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-22T17:49:58.540+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:49:58.540+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-22T17:49:58.565+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:49:58.564+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-22T17:49:58.565+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-22T17:49:58.589+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.137 seconds
[2024-11-22T17:50:28.857+0000] {processor.py:186} INFO - Started process (PID=1188) to work on /opt/airflow/dags/obs.py
[2024-11-22T17:50:28.858+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-22T17:50:28.862+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:50:28.862+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-22T17:50:28.887+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:50:28.886+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-22T17:50:28.888+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-22T17:50:28.906+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.055 seconds
[2024-11-22T17:50:59.152+0000] {processor.py:186} INFO - Started process (PID=1196) to work on /opt/airflow/dags/obs.py
[2024-11-22T17:50:59.199+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-22T17:50:59.203+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:50:59.202+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-22T17:50:59.226+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:50:59.225+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-22T17:50:59.227+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-22T17:50:59.247+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.101 seconds
[2024-11-22T17:51:29.500+0000] {processor.py:186} INFO - Started process (PID=1204) to work on /opt/airflow/dags/obs.py
[2024-11-22T17:51:29.501+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-22T17:51:29.504+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:51:29.504+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-22T17:51:29.527+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:51:29.526+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-22T17:51:29.528+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-22T17:51:29.549+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.055 seconds
[2024-11-22T17:51:59.814+0000] {processor.py:186} INFO - Started process (PID=1212) to work on /opt/airflow/dags/obs.py
[2024-11-22T17:51:59.815+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-22T17:51:59.819+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:51:59.819+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-22T17:51:59.842+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:51:59.841+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-22T17:51:59.843+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-22T17:51:59.862+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.054 seconds
[2024-11-22T17:52:30.125+0000] {processor.py:186} INFO - Started process (PID=1220) to work on /opt/airflow/dags/obs.py
[2024-11-22T17:52:30.126+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-22T17:52:30.128+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:52:30.128+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-22T17:52:30.152+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:52:30.151+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-22T17:52:30.152+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-22T17:52:30.173+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.054 seconds
[2024-11-22T17:53:00.429+0000] {processor.py:186} INFO - Started process (PID=1228) to work on /opt/airflow/dags/obs.py
[2024-11-22T17:53:00.476+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-22T17:53:00.482+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:53:00.481+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-22T17:53:00.506+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:53:00.505+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-22T17:53:00.506+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-22T17:53:00.527+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.104 seconds
[2024-11-22T17:53:30.786+0000] {processor.py:186} INFO - Started process (PID=1236) to work on /opt/airflow/dags/obs.py
[2024-11-22T17:53:30.787+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-22T17:53:30.791+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:53:30.791+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-22T17:53:30.814+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:53:30.813+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-22T17:53:30.815+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-22T17:53:30.835+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.055 seconds
[2024-11-22T17:54:01.090+0000] {processor.py:186} INFO - Started process (PID=1244) to work on /opt/airflow/dags/obs.py
[2024-11-22T17:54:01.136+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-22T17:54:01.139+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:54:01.139+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-22T17:54:01.163+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:54:01.161+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-22T17:54:01.163+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-22T17:54:01.184+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.100 seconds
[2024-11-22T17:54:31.447+0000] {processor.py:186} INFO - Started process (PID=1251) to work on /opt/airflow/dags/obs.py
[2024-11-22T17:54:31.448+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-22T17:54:31.452+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:54:31.451+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-22T17:54:31.477+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:54:31.476+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-22T17:54:31.477+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-22T17:54:31.497+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.056 seconds
[2024-11-22T17:55:01.763+0000] {processor.py:186} INFO - Started process (PID=1259) to work on /opt/airflow/dags/obs.py
[2024-11-22T17:55:01.764+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-22T17:55:01.768+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:55:01.768+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-22T17:55:01.792+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:55:01.791+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-22T17:55:01.792+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-22T17:55:01.814+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.057 seconds
[2024-11-22T17:55:32.077+0000] {processor.py:186} INFO - Started process (PID=1267) to work on /opt/airflow/dags/obs.py
[2024-11-22T17:55:32.077+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-22T17:55:32.080+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:55:32.080+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-22T17:55:32.105+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:55:32.104+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-22T17:55:32.106+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-22T17:55:32.125+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.055 seconds
[2024-11-22T17:56:02.389+0000] {processor.py:186} INFO - Started process (PID=1275) to work on /opt/airflow/dags/obs.py
[2024-11-22T17:56:02.436+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-22T17:56:02.441+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:56:02.440+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-22T17:56:02.466+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:56:02.465+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-22T17:56:02.466+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-22T17:56:02.487+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.106 seconds
[2024-11-22T17:56:32.751+0000] {processor.py:186} INFO - Started process (PID=1283) to work on /opt/airflow/dags/obs.py
[2024-11-22T17:56:32.752+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-22T17:56:32.756+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:56:32.756+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-22T17:56:32.782+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:56:32.781+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-22T17:56:32.783+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-22T17:56:32.805+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.061 seconds
[2024-11-22T17:57:03.067+0000] {processor.py:186} INFO - Started process (PID=1290) to work on /opt/airflow/dags/obs.py
[2024-11-22T17:57:03.115+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-22T17:57:03.118+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:57:03.117+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-22T17:57:03.147+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:57:03.145+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-22T17:57:03.148+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-22T17:57:03.170+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.109 seconds
[2024-11-22T17:57:33.428+0000] {processor.py:186} INFO - Started process (PID=1298) to work on /opt/airflow/dags/obs.py
[2024-11-22T17:57:33.429+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-22T17:57:33.433+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:57:33.432+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-22T17:57:33.458+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:57:33.456+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-22T17:57:33.459+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-22T17:57:33.481+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.058 seconds
[2024-11-22T17:58:03.740+0000] {processor.py:186} INFO - Started process (PID=1306) to work on /opt/airflow/dags/obs.py
[2024-11-22T17:58:03.742+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-22T17:58:03.746+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:58:03.745+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-22T17:58:03.774+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:58:03.772+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-22T17:58:03.774+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-22T17:58:03.796+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.062 seconds
[2024-11-22T17:58:34.054+0000] {processor.py:186} INFO - Started process (PID=1314) to work on /opt/airflow/dags/obs.py
[2024-11-22T17:58:34.055+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-22T17:58:34.058+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:58:34.058+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-22T17:58:34.081+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:58:34.080+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-22T17:58:34.081+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-22T17:58:34.104+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.056 seconds
[2024-11-22T17:59:04.363+0000] {processor.py:186} INFO - Started process (PID=1322) to work on /opt/airflow/dags/obs.py
[2024-11-22T17:59:04.411+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-22T17:59:04.415+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:59:04.414+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-22T17:59:04.441+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:59:04.440+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-22T17:59:04.441+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-22T17:59:04.463+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.106 seconds
[2024-11-22T17:59:34.729+0000] {processor.py:186} INFO - Started process (PID=1330) to work on /opt/airflow/dags/obs.py
[2024-11-22T17:59:34.730+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-22T17:59:34.734+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:59:34.733+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-22T17:59:34.757+0000] {logging_mixin.py:190} INFO - [2024-11-22T17:59:34.756+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-22T17:59:34.758+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-22T17:59:34.780+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.057 seconds
