[2024-11-23T23:47:13.341+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-23T23:47:13.358+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: trigger_cdm_task.trigger_cdm_task manual__2024-11-23T23:47:11.859970+00:00 [queued]>
[2024-11-23T23:47:13.365+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: trigger_cdm_task.trigger_cdm_task manual__2024-11-23T23:47:11.859970+00:00 [queued]>
[2024-11-23T23:47:13.366+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-11-23T23:47:13.377+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): trigger_cdm_task> on 2024-11-23 23:47:11.859970+00:00
[2024-11-23T23:47:13.384+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=555) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-23T23:47:13.385+0000] {standard_task_runner.py:72} INFO - Started process 556 to run task
[2024-11-23T23:47:13.386+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'trigger_cdm_task', 'trigger_cdm_task', 'manual__2024-11-23T23:47:11.859970+00:00', '--job-id', '69', '--raw', '--subdir', 'DAGS_FOLDER/cdm.py', '--cfg-path', '/tmp/tmpaalc92va']
[2024-11-23T23:47:13.387+0000] {standard_task_runner.py:105} INFO - Job 69: Subtask trigger_cdm_task
[2024-11-23T23:47:13.432+0000] {task_command.py:467} INFO - Running <TaskInstance: trigger_cdm_task.trigger_cdm_task manual__2024-11-23T23:47:11.859970+00:00 [running]> on host de82a0198583
[2024-11-23T23:47:13.502+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='trigger_cdm_task' AIRFLOW_CTX_TASK_ID='trigger_cdm_task' AIRFLOW_CTX_EXECUTION_DATE='2024-11-23T23:47:11.859970+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-23T23:47:11.859970+00:00'
[2024-11-23T23:47:13.503+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-23T23:47:13.515+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/cdm.py", line 33, in start_cdm_job
    .build()
     ^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/huaweicloudsdkcore/client.py", line 194, in build
    self._endpoints += self._region.endpoints
                       ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'endpoints'
[2024-11-23T23:47:13.529+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=trigger_cdm_task, task_id=trigger_cdm_task, run_id=manual__2024-11-23T23:47:11.859970+00:00, execution_date=20241123T234711, start_date=20241123T234713, end_date=20241123T234713
[2024-11-23T23:47:13.543+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-23T23:47:13.544+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 69 for task trigger_cdm_task ('str' object has no attribute 'endpoints'; 556)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/cdm.py", line 33, in start_cdm_job
    .build()
     ^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/huaweicloudsdkcore/client.py", line 194, in build
    self._endpoints += self._region.endpoints
                       ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'endpoints'
[2024-11-23T23:47:13.559+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-23T23:47:13.582+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-23T23:47:13.583+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
